const embedded=JSON.parse(document.getElementById('portfolio-snapshot')?.textContent||'{"works":[]}');
let dbPromise;
function decodeFile(w){const bytes=Uint8Array.from(atob(w.bytes),c=>c.charCodeAt(0));const {bytes:encoded,...row}=w;return {...row,history:(w.history||[]).map(decodeFile),file:new Blob([bytes],{type:w.type||'application/octet-stream'})};}
const openDB=()=>dbPromise||(dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('UPLA_Portafolio_BD2_Offline'+(embedded.copyId?'_'+embedded.copyId:''),1);r.onupgradeneeded=()=>{r.result.createObjectStore('works',{keyPath:'id'});r.result.createObjectStore('settings');};r.onsuccess=()=>{const db=r.result;const tx=db.transaction('works','readwrite'),store=tx.objectStore('works');for(const w of embedded.works){const check=store.get(w.id);check.onsuccess=()=>{if(!check.result)store.put(decodeFile(w));};}tx.oncomplete=()=>resolve(db);tx.onerror=()=>reject(new Error('No se pudo abrir la copia. Revisa el espacio disponible.'));};r.onerror=()=>reject(new Error('No se puede guardar en este navegador. Abre el HTML en Chrome o Edge y permite el almacenamiento local.'));}));
async function transaction(store,mode,operation){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode);let result;const r=operation(tx.objectStore(store));r.onsuccess=()=>{result=r.result};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(new Error('No se pudo guardar. Revisa el espacio disponible del navegador.'));tx.onabort=()=>reject(new Error('La operación no se completó.'));});}
const getAll=()=>transaction('works','readonly',s=>s.getAll());
window.portfolioGetAll=getAll;
window.portfolioFile=async(id,version)=>{const w=await transaction('works','readonly',s=>s.get(id));if(!w)throw Error('Archivo no encontrado');return version===undefined?w:(w.history||[])[version];};
let isAdmin=false;
const answer=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
const originalFetch=window.fetch.bind(window);
window.fetch=async function(input,options={}){if(typeof input!=='string'||!input.startsWith('/api/portfolio'))return originalFetch(input,options);try{
if(!options.method||options.method==='GET'){const works=await getAll();const profile=await transaction('settings','readonly',s=>s.get('profile'));return answer({works:works.map(({file,history,...w})=>({...w,history:(history||[]).map(({file,history,...h})=>h)})).sort((a,b)=>b.created.localeCompare(a.created)),profile,admin:isAdmin});}
if(options.body instanceof FormData){if(isAdmin)return answer({error:'Vuelve al perfil estudiante para subir trabajos'},403);const d=options.body,file=d.get('file');if(d.get('action')==='replace'){const old=await transaction('works','readonly',s=>s.get(d.get('id')));if(!old)return answer({error:'Trabajo no encontrado'},404);const name=String(d.get('name')||'').trim(),description=String(d.get('description')||'').trim();if(!name||name.length>200||description.length>1000)return answer({error:'Revisa el nombre y la descripción'},400);if(file!==null&&(!(file instanceof File)||!file.size||file.size>20*1024*1024))return answer({error:'El archivo debe pesar entre 1 byte y 20 MB'},400);const {history:previous,...snapshot}=old;const row={...old,history:[...(previous||[]),snapshot],name,description,file:file||old.file,size:file?file.size:old.size,type:file?file.type:old.type,updated:new Date().toISOString(),grade:null,comment:'',seen:0};delete row.graded;await transaction('works','readwrite',s=>s.put(row));return answer({ok:true});}if(!(file instanceof File)||!file.size||file.size>20*1024*1024)return answer({error:'El archivo debe pesar entre 1 byte y 20 MB'},400);const row={id:String(d.get('id')||crypto.randomUUID()),unit:Number(d.get('unit')),week:Number(d.get('week')),day:d.get('day'),name:String(d.get('name')||file.name),description:String(d.get('description')||''),type:file.type,size:file.size,created:new Date().toISOString(),grade:null,comment:'',seen:0,file};await transaction('works','readwrite',s=>s.put(row));return answer({ok:true});}
const d=JSON.parse(options.body);
if(['delete','feature','cover','restore'].includes(d.action)){if(isAdmin)return answer({error:'Vuelve al perfil estudiante'},403);const w=await transaction('works','readonly',s=>s.get(d.id));if(!w)return answer({error:'Trabajo no encontrado'},404);if(d.action==='delete'){await transaction('works','readwrite',s=>s.delete(d.id));return answer({ok:true});}if(d.action==='feature')await transaction('works','readwrite',s=>s.put({...w,featured:!w.featured}));if(d.action==='cover'){if(typeof d.cover!=='string'||!/^data:image\/(png|jpeg|webp);base64,/.test(d.cover)||d.cover.length>2800000)return answer({error:'Usa una portada PNG, JPEG o WebP de máximo 2 MB'},400);await transaction('works','readwrite',s=>s.put({...w,cover:d.cover}));}if(d.action==='restore'){const h=(w.history||[])[d.version];if(!h)return answer({error:'Versión no encontrada'},404);const {history,...current}=w;await transaction('works','readwrite',s=>s.put({...h,id:w.id,history:[...history,current],updated:new Date().toISOString(),grade:null,comment:'',seen:0}));}return answer({ok:true});}
if(d.action==='login'){if(d.user!=='ADMIN'||d.password!=='ADMIN')return answer({error:'Usuario o contraseña incorrectos'},401);isAdmin=true;return answer({ok:true});}
if(d.action==='logout'){isAdmin=false;return answer({ok:true});}
if(d.action==='profile'){await transaction('settings','readwrite',s=>s.put(d.profile,'profile'));return answer({ok:true});}
if(d.action==='grade'){if(!isAdmin)return answer({error:'Ingresa como administrador'},403);if(!Number.isInteger(d.grade)||d.grade<0||d.grade>20)return answer({error:'Ingresa una nota entera de 0 a 20'},400);const w=await transaction('works','readonly',s=>s.get(d.id));if(!w)return answer({error:'Trabajo no encontrado'},404);await transaction('works','readwrite',s=>s.put({...w,grade:d.grade,comment:d.comment,seen:0,graded:new Date().toISOString()}));return answer({ok:true});}
if(d.action==='seen'){for(const w of await getAll())if(w.grade!==null)await transaction('works','readwrite',s=>s.put({...w,seen:1}));return answer({ok:true});}return answer({error:'Acción no válida'},400);
}catch(e){return answer({error:e.message||'El almacenamiento local no está disponible'},503);}};
document.addEventListener('click',async e=>{const a=e.target.closest('a');if(!a?.getAttribute('href')?.startsWith('/api/portfolio?file='))return;e.preventDefault();try{const id=a.getAttribute('href').split('file=')[1];const w=await window.portfolioFile(id);if(!w?.file)throw Error('Archivo no encontrado');const url=URL.createObjectURL(w.file),link=document.createElement('a');link.href=url;link.download=w.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}catch(err){alert(err.message);}});
