// Vista de revisión integrada. La autorización real corresponde a bd2_save en Supabase.
export function createAdminView({state,esc,icon,button,fmtDate,fmtBytes,authenticated}) {
  const filters={status:'pending',unit:'all',search:''};
  function rows(){return state.works.filter(w=>(filters.unit==='all'||w.unit===Number(filters.unit))&&(filters.status==='all'||(filters.status==='pending'?w.grade==null:w.grade!=null))&&(`${w.name} ${w.description||''}`).toLocaleLowerCase('es').includes(filters.search.trim().toLocaleLowerCase('es'))).sort((a,b)=>String(b.created).localeCompare(String(a.created)));}
  function results(){const list=rows();return `<p class="admin-result-count" role="status">${list.length} ${list.length===1?'entrega encontrada':'entregas encontradas'}</p>${list.length?list.map(w=>`<article class="review-card"><div class="review-file">${icon('file')}</div><div class="review-info"><div class="review-meta"><span>UNIDAD ${w.unit} · SEMANA ${w.week}</span><span>${w.day}</span></div><h3>${esc(w.name)}</h3><p>${esc(w.description||'Sin descripción adicional.')}</p><small>Entregado el ${fmtDate(w.created)} · ${fmtBytes(w.size)} · Versión ${w.revision||1}</small></div><div class="review-outcome"><span class="review-status ${w.grade==null?'pending':'done'}">${w.grade==null?'Por revisar':'Evaluado'}</span><strong>${w.grade==null?'—':`${w.grade}<small> / 20</small>`}</strong></div><div class="review-actions">${button('Abrir archivo','preview','eye','small',`data-id="${esc(w.id)}"`)}${button(w.grade==null?'Evaluar trabajo':'Editar evaluación','grade','edit','primary small',`data-id="${esc(w.id)}"`)}${button('Versiones','history','history','small quiet',`data-id="${esc(w.id)}"`)}</div>${w.grade!=null?`<div class="review-feedback"><span>Comentario enviado a Yuber</span><p>${esc(w.comment||'Sin observaciones adicionales.')}</p><small>${w.seen?'Leído por el estudiante':'Pendiente de lectura'} · ${fmtDate(w.graded||w.updated)}</small></div>`:''}</article>`).join(''):`<div class="admin-empty">${icon('check')}<h3>${state.works.length?'No hay entregas con estos filtros':'Todavía no hay trabajos recibidos'}</h3><p>${state.works.length?'Cambia el estado o la unidad para consultar otras entregas.':'Los trabajos aparecerán aquí cuando Yuber pulse Guardar trabajos desde su cuenta.'}</p></div>`}`;}
  function render(){
    if(!authenticated()||!state.admin)return `<section class="admin-gate panel"><span class="tile-icon">${icon('shield')}</span><div class="eyebrow">ACCESO DE REVISIÓN</div><h1>Administrador</h1><p>Revisa las entregas de Yuber, registra una nota y envía tus observaciones desde este mismo portafolio.</p>${button('Ingresar como administrador','admin-login','lock','primary')}<a href="#inicio" class="text-btn">Volver al portafolio</a></section>`;
    const graded=state.works.filter(w=>w.grade!=null),pending=state.works.length-graded.length;
    return `<section class="admin-layout"><aside class="admin-sidebar"><div class="admin-emblem">${icon('shield')}</div><span class="eyebrow">BASE DE DATOS II</span><h2>Área de<br>revisión</h2><p>Administrador</p><div class="admin-side-links"><a href="#administrador" aria-current="page">${icon('folder')}Trabajos de Yuber</a><button data-action="admin-filter-all">${icon('check')}Todas las evaluaciones</button><button data-action="refresh">${icon('refresh')}Actualizar entregas</button></div><div class="admin-student"><span>PORTAFOLIO ASIGNADO</span><strong>Yuber</strong><small>Ingeniería de Sistemas · UPLA</small></div><a href="#inicio" class="admin-back">${icon('arrow')}Ver portafolio</a><button class="btn quiet wide" data-action="logout">${icon('logout')}Cerrar sesión</button></aside><div class="admin-content"><header class="admin-heading"><div><div class="eyebrow">ACOMPAÑAR EL APRENDIZAJE</div><h1>Trabajos recibidos<span>.</span></h1><p>Una revisión clara ayuda a mejorar la siguiente entrega.</p></div><span class="admin-live">${icon('cloud')}<span data-status-title>Comprobando conexión…</span></span></header><div class="admin-metrics"><article><span>Entregas</span><strong>${state.works.length}</strong><small>Guardadas por Yuber</small></article><article><span>Por revisar</span><strong>${pending}</strong><small>Esperan tu evaluación</small></article><article><span>Evaluadas</span><strong>${graded.length}</strong><small>Con nota registrada</small></article><article><span>Promedio</span><strong>${graded.length?(graded.reduce((s,w)=>s+w.grade,0)/graded.length).toFixed(1):'—'}<small> / 20</small></strong><small>De las entregas evaluadas</small></article></div><section class="admin-inbox"><div class="admin-inbox-heading"><h2>Bandeja de entregas</h2><span>Nota + comentario → notificación al estudiante</span></div><div class="admin-filters"><label>Buscar trabajo<input type="search" id="admin-search" placeholder="Título o descripción" value="${esc(filters.search)}"></label><label>Estado<select id="admin-status"><option value="pending" ${filters.status==='pending'?'selected':''}>Por revisar</option><option value="graded" ${filters.status==='graded'?'selected':''}>Evaluados</option><option value="all" ${filters.status==='all'?'selected':''}>Todos</option></select></label><label>Unidad<select id="admin-unit"><option value="all">Todas las unidades</option>${[1,2,3,4].map(u=>`<option value="${u}" ${filters.unit===String(u)?'selected':''}>Unidad ${u}</option>`).join('')}</select></label></div><div id="admin-results">${results()}</div></section><p class="admin-sync-note">La lista se consulta automáticamente cada 15 segundos mientras esta ventana está activa. Las evaluaciones se confirman al guardarlas.</p></div></section>`;
  }
  function update(){const el=document.getElementById('admin-results');if(el)el.innerHTML=results();}
  document.addEventListener('input',e=>{if(e.target.id==='admin-search'){filters.search=e.target.value;update();}});
  document.addEventListener('change',e=>{if(e.target.id==='admin-status'){filters.status=e.target.value;update();}if(e.target.id==='admin-unit'){filters.unit=e.target.value;update();}});
  return {render,filters};
}
