// Personajes vectoriales articulados: desplazamiento, salto, defensa y ataque.
// Son animaciones de la interfaz, sin videos ni servicios externos.
function fighter(kind='gojo'){
 const yuji=kind==='yuji',robot=kind==='robot',rival=kind==='rival';
 const skin=robot||rival?'#d9e6e9':'#efbca7',suit=yuji?'#253750':robot?'#93bba9':rival?'#828dc9':'#292447',hair=yuji?'#ea8e95':'#edf1ff',glow=robot?'#b9ff62':rival?'#ffb981':yuji?'#67e5ff':'#bc99ff';
 return `<svg class="fighter-svg" viewBox="0 0 120 170" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><ellipse cx="60" cy="158" rx="36" ry="6" fill="#000" opacity=".28"/><g class="fighter-body" stroke="#111b30" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><g class="back-arm"><path d="M39 84 22 106 33 121" fill="none" stroke="${suit}" stroke-width="14"/><circle cx="33" cy="121" r="7" fill="${skin}"/></g><g class="leg leg-one"><path d="M47 112 41 140 28 149" fill="none" stroke="${suit}" stroke-width="17"/><path d="m22 149 20-1 3 8H21Z" fill="#111b30"/></g><g class="leg leg-two"><path d="m68 112 10 21-2 20" fill="none" stroke="${suit}" stroke-width="17"/><path d="m70 149 19 3 3 6H70Z" fill="#111b30"/></g><path d="M40 72Q57 65 76 74L81 115Q60 124 36 114Z" fill="${suit}"/><path d="M44 79 52 116" fill="none" stroke="${glow}" stroke-width="2" opacity=".55"/><rect x="47" y="54" width="22" height="21" rx="6" fill="${skin}"/><rect x="31" y="21" width="51" height="47" rx="18" fill="${skin}"/>${robot||rival?`<rect x="25" y="16" width="63" height="53" rx="17" fill="${skin}"/><rect x="34" y="29" width="45" height="26" rx="8" fill="#101f29"/><path d="M44 35v10m23-10v10" stroke="${glow}" stroke-width="5"/><path d="M54 16V5h8" fill="none" stroke="${glow}"/><circle cx="65" cy="6" r="4" fill="${glow}"/><path d="m40 73 30 1-3 12-25 2" fill="${glow}"/>`:`<path d="M29 40 22 27 34 27 30 10 43 18 48 3 58 14 72 4 73 20 88 17 81 39 70 28 44 31Z" fill="${hair}"/>${yuji?`<path d="M39 43h8m18 0h8" stroke-width="4"/><path d="M39 76 48 65 68 67 79 79 70 92 42 88Z" fill="#be454e"/>`:`<path d="m30 37 50-4 3 16-50 5Z" fill="#121526"/><path d="m38 73 5-13 31 6 3 16Z" fill="#30294f"/>`}<path d="M57 56q6 3 11-1" fill="none" stroke-width="2"/>`}<g class="front-arm"><path d="M73 81 89 95 105 84" fill="none" stroke="${suit}" stroke-width="14"/><circle cx="105" cy="83" r="8" fill="${skin}"/><circle class="hand-energy" cx="108" cy="80" r="16" stroke="${glow}" fill="${glow}" fill-opacity=".15" stroke-width="2"/></g></g></svg>`;
}
export function characters(){return `<section class="character-section"><div class="arena-heading"><div><span class="eyebrow">MI ZONA DE DESCANSO</span><h2>Un pequeño duelo<br>entre entregas.</h2><p>Un toque de mis universos favoritos, con personajes en movimiento.</p></div><div class="arena-buttons"><button class="btn small" data-action="duel-replay">Repetir duelo</button><button class="btn small quiet" data-action="characters-toggle" aria-pressed="true">Ocultar personajes</button></div></div><div class="duel-arena" aria-label="Escena animada de personajes; puedes pausar el movimiento en el pie de página"><div class="arena-sky"></div><div class="arena-moon"></div><div class="arena-mountains"></div><div class="arena-floor"></div><div class="arena-hud"><span data-jjk>GOJO / YUJI</span><span data-game>PLAYER 01 / PLAYER 02</span><span>EXHIBICIÓN</span></div><div class="duel-fighter left-fighter"><div data-jjk>${fighter('gojo')}</div><div data-game>${fighter('robot')}</div></div><div class="duel-fighter right-fighter"><div data-jjk>${fighter('yuji')}</div><div data-game>${fighter('rival')}</div></div><div class="energy-shot shot-one"></div><div class="energy-shot shot-two"></div><div class="duel-impact"></div><div class="arena-caption"><span data-jjk>Concentración · Energía · Movimiento</span><span data-game>Salta · Explora · Siguiente nivel</span></div></div></section>`;}
export function installCharacters(){
 const stage=document.createElement('div');stage.id='character-stage';stage.setAttribute('aria-hidden','true');stage.innerHTML=`<div class="screen-runner"><div data-jjk>${fighter('gojo')}</div><div data-game>${fighter('robot')}</div></div><div class="screen-runner runner-two"><div data-jjk>${fighter('yuji')}</div><div data-game>${fighter('rival')}</div></div>`;document.body.append(stage);
 try{document.body.classList.toggle('characters-off',localStorage.getItem('yuber-characters-off')==='true');}catch{}
 const labels=()=>document.querySelectorAll('[data-action="characters-toggle"]').forEach(b=>{const on=!document.body.classList.contains('characters-off');b.textContent=on?'Ocultar personajes':'Mostrar personajes';b.setAttribute('aria-pressed',String(on));});
 const observer=new MutationObserver(labels);observer.observe(document.getElementById('main'),{childList:true});
 document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;
 if(a==='characters-toggle'){const off=document.body.classList.toggle('characters-off');try{localStorage.setItem('yuber-characters-off',String(off));}catch{}labels();}
 if(a==='duel-replay'){const arena=document.querySelector('.duel-arena');arena?.classList.remove('duel-restart');void arena?.offsetWidth;arena?.classList.add('duel-restart');const effects=arena?.getAnimations({subtree:true})||[];effects.forEach(effect=>{effect.currentTime=0;});}
 });
}
